SELECT TOP (1000) [ProStudentID]
      ,[Title]
      ,[Gender]
      ,[Surname]
      ,[PrevSurname]
      ,[Firstname]
      ,[DoB]
      ,[CorrAddress]
      ,[Postcode]
      ,[Email]
      ,[Mobile]
      ,[BirthCountry]
      ,[PStatement]
  FROM [MMU_Admissions].[dbo].[ProStudent]
